services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./init-ollama.sh:/init-ollama.sh
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-0.0.0.0}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  ollama-init:
    image: ollama/ollama:latest
    container_name: ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ./init-ollama.sh:/init-ollama.sh
    environment:
      - OLLAMA_HOST=ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    entrypoint: ["/bin/sh"]
    command: ["-c", "chmod +x /init-ollama.sh && /init-ollama.sh"]
    restart: "no"

  web-ui:
    build: ./web-ui
    container_name: ollama-web-ui
    ports:
      - "${WEB_UI_PORT:-8080}:8080"
    depends_on:
      - ollama-init
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1}
    restart: unless-stopped

volumes:
  ollama_data: